config/routes.rb
Wcadono::Application.routes.draw do
  root :to => 'board#show'

  resources :board do
      resources :tasks
  end
end

app/models/board.rb
class Board
  include Mongoid::Document
  field :name, type: String

  validates_presence_of :name

  def self.default_board
    Board.first || Board.create(name: "Default Name")
  end
end

app/models/task.rb
class Task
  include Mongoid::Document
  field :title, type: String
  field :description, type: String

  validates_presence_of :title, :description
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/board_controller.rb
class BoardController < ApplicationController
  def show
    @board = Board.default_board
  end
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  before_filter :set_board

  def new
    @task = Task.new
  end

  def create
    @task = Task.new
    redirect_to board_path(@board.id)
  end

  private 

  def set_board
    puts "params #{params.inspect}"
    @board = Board.find(params[:board_id])
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/board/show.html.haml
%h1= @board.name
%p
  Use table to show board...

= link_to "Add task", new_board_task_path(@board)

- @board.tasks.each do |task|
  %p=task.title


%table#main-table
  %thead
    %tr
      %td
        Applications
      %td
        Backlog
      %td
        Todo
      %td
        Work
      %td
        ToReview
      %td
        ToTest
      %td
        ToDeliver
  %tbody
    %tr
      %td
        Application 1
      %td
        task A
      %td
        task B<br/>
        task C
      %td
      %td
      %td
        task D
      %td
    %tr
      %td
        Application 2
      %td
        task E<br/>
        task F<br/>
        task G<br/>
      %td
      %td
        task H
      %td
        task I<br/>
        task J<br/>
      %td
        task K

app/views/layouts/application.html.haml
!!! 5
%html
  %head
    %title
      Wcadono
    = stylesheet_link_tag    "application"
    = javascript_include_tag "application" 
    = csrf_meta_tags

  %body
    #header
      = link_to "Home", root_path
    #content= yield 
    #footer

app/views/tasks/create.html.haml
%p 
  Task created

app/views/tasks/new.html.haml
%p
  new tasks

= form_for([@board, @task]) do |t|
  = t.label :title, 'Title'
  = t.text_field :title
  = t.label :description, 'Description'
  = t.text_field :description 
  = t.submit 